### ISSUE TITLE
Update runtime to 5.13

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.notepadqq.Notepadqq#4]

**Comment by scx** [comment]
I see no reason to update the KDE runtime to _5.13_.
I have already explained why the current stable branch (`1.4.8`) won't be updated to KDE _5.12_.
https://github.com/flathub/com.notepadqq.Notepadqq/issues/1#issuecomment-469473689

We are going to release `2.0.0~beta` in the beta channel very soon, but it will use KDE _5.12_.
First of all, Qt 5.12 is an LTS release, while 5.13 is not.
https://en.wikipedia.org/w/index.php?title=Qt_version_history&oldid=917412339#Qt_5
And what's worse, KDE _5.13_ doesn't even provide QtWebEngine. There are plans to release `io.qt.qtwebengine.BaseApp`, but it is currently not available.
https://github.com/flathub/flathub/pull/1163

Next time, please do some research before opening a new issue.
